### PR TITLE
measuring target margin for takeover – closes #338

### LINKED ISSUE #338: Bottom text cut off on Welcome page
Welcome page includes buttons in a container fixed to the bottom of the view. On mobile, more padding is need to avoid blocking some content. 

screen shot 2017-04-21 at 2 46 36 pm

### PR DESCRIPTION
**Pull request by gvn**
measuring target margin for takeover – closes #338

### CODE REVIEW

**Comment by gvn** [comment]
Yeah, it's technically less supported, but we're using it already so sure.

**Comment by alanmoo** [comment]
My thoughts exactly. Plus it degrades to a totally fine experience.

**Comment by gvn** [comment]
Ok, sticky it is. R?

**Comment by gvn** [comment]
Margin reduced...

**Pull request merged**
