### PR TITLE
updating News schema

### PR DESCRIPTION
**Pull request by gvn**
Related to #173

### CODE REVIEW

**Comment by gvn** [comment]
@gideonthomas – I guess I spoke too soon about this schema being final. One more field for `author`.

**Comment by gvn** [comment]
Ok, also another field for `glyph`, which is an image URL.

**Comment by gvn** [comment]
And...also a `featured` boolean.

**Comment by gvn** [comment]
That's a good question for design I suppose. Currently there are 4, but I don't know if that's the max. @xmatthewx thoughts?

**Comment by gvn** [comment]
Based on Slack: There will be 4 featured items.

**Comment by gideonthomas** [comment]
@gvn, will they be uploading `glyph` through the admin interface or is it just a url to an image somewhere on the web?

**Comment by gvn** [comment]
@gideonthomas It should be uploaded via the CMS

**Pull request merged**
