### PR TITLE
Replace text value with variable - changed text color to black

### LINKED ISSUE #267: QA: Global Issue - text color
This issue affects many pages:

- [x] Copy is rendering dark gray in some pages
gray-copy
It seems the solution for this is in the css of body (currently is set to have a different color than black):
screen shot 2017-04-05 at 6 22 08 pm

- [ ] Other examples of gray copy (those ones are very close to black but not #000000)
image
image

### PR DESCRIPTION
**Pull request by taisdesouzalessa**
Fixes #267

### CODE REVIEW

**Comment by taisdesouzalessa** [comment]
cc: @mmmavis here are the latest changes

**Comment by mmmavis** [comment]
Hey @taisdesouzalessa, woohooo another PR! 🍻 

I think we don't have to override the text color again since we already set `h1, h2, h3, h4, h5, h6` to be `$black`. See https://github.com/mozilla/network/blob/master/source/sass/type.scss#L1-L7

screen shot 2017-04-17 at 3 25 35 pm

Notice in the dev tool `color: #000` is crossed out and later being set again with the same value.

/cc @gvn in case I'm pointing @taisdesouzalessa to the wrong direction 😉

**Comment by gvn** [comment]
That's right, you can probably just remove those color overrides entirely.

**Comment by taisdesouzalessa** [comment]
@mmmavis I made the changes as requested. Please review :).

**Comment by gvn** [comment]
If you add branches to this repo for PRs, please delete them after they're merged. 🎉

**Pull request merged**
