### PR TITLE
full width signup for opportunity pages - #754

### PR DESCRIPTION
**Pull request by gvn**

### CODE REVIEW

**Comment by gvn** [comment]
@cadecairos - "snyk test requires an authenticated account. Please run `snyk auth` and try again." 

Any idea how to fix that?

**Comment by mmmavis** [comment]
Looks good. Let's wait until the `snyk auth` thing gets sorted out before we merge this PR.

**Comment by cadecairos** [comment]
Oh, that's odd,  this was just working.  I'll have a look ASAP.

**Comment by cadecairos** [comment]
So it seems that Appveyor and Travis will only decrypt secure environment variables if the branch making the pull request is the same as the origin.

We have two options: back out the patch, and make it something we can run manually or we can make branches on the origin and open PRs from there.

**Comment by gvn** [comment]
Since contributors don't have the option to open PRs on this repo we should figure out a way to make cross-repo PRs validate.

**Comment by gvn** [comment]
Re-opening as #807

**Pull request closed without merging**
