### PR TITLE
allow menu scroll - fixes #277

### LINKED ISSUE #277: QA: Menu - IMPORTANT
- [ ] ﻿Mobile menu is not stacking on iOS (screenshot from iPhone-browsers: Firefox and Safari) - iPhone 6. **IMPORTANT**: 
screen shot 2017-04-06 at 3 29 46 pm

- [ ] ﻿Desktop Menu doesn't scroll which is an usability problem for users with smaller screens **IMPORTANT**: 
desktop-menu

### PR DESCRIPTION
**Pull request by gvn**
Fixes #277

### CODE REVIEW

**Comment by alanmoo** [comment]
This still doesn't stack the menu items on iOS 10, it's a horizontal scroll. (The scroll does work, but I feel like that's not the intended behavior).  Can you clarify the expected behavior?

**Comment by gvn** [comment]
Can you attach a screenshot? What device / browser?

**Comment by alanmoo** [comment]
iPhone 6/iOS 10.3.2
img_3259

**Comment by gvn** [comment]
So, without having an iPhone 6 to test, this is the closest I can get, which doesn't repro:

screen shot 2017-04-13 at 2 46 18 pm

I think we should probably land this and file a follow-on for anyone with an iPhone 6 to tackle.

**Comment by gvn** [comment]
FWIW: It wraps on my Nexus 5.

**Comment by alanmoo** [comment]
Safari's responsive design mode replicates the issue (iPhone 6S setting)

**Comment by alanmoo** [comment]
You might just need a `col-12 col-sm-auto` on one of the columns, instead of simply `col`

**Comment by gvn** [comment]
@alanmoo R?

**Pull request merged**
