### PR TITLE
remove build signal for jenkins

### PR DESCRIPTION
**Pull request by cadecairos**
This PR removes the code that wires up signals on models, and the debounce/throttle code for triggering Jenkins builds remotely.

### CODE REVIEW

**Comment by gvn** [comment]
We'll still need the build to re-run when models' data changes. Is that what this is taking out?

**Comment by cadecairos** [comment]
right, I had forgotten this was still statically generated. I'll keep the signals and integrate the signals with Heroku's build and deploy API

**Comment by gvn** [comment]
Do you want to do that in this PR?

**Comment by cadecairos** [comment]
yes, I'll work on this today

**Comment by cadecairos** [comment]
@gvn I have force pushed a change to this branch. It updates the `build_static_site` method to use Heroku's Build API.

**Comment by gvn** [comment]
This gets a "LGTM" R+ since I'm not really able to test...

**Pull request merged**
