### PR TITLE
Adding back package-lock

### LINKED ISSUE #536: Add package-lock back
Due to what appears to be a bug in npm, we're gitignoring `package-lock.json` and also removing it as a `preinstall` command.

Once npm is fixed we should add it back.

### PR DESCRIPTION
**Pull request by gvn**
Closes #536 

It seems like this is working properly now. I've tried locally with npm `5.3.0` and node `8.1.4`.

### CODE REVIEW

**Comment by gvn** [comment]
@Pomax if you don't have time to review can you re-assign the review to someone else? Thx!

**Comment by Pomax** [comment]
Things work for me locally but it might make sense to push this as a branch 'gh-536` on the mozilla repo instead, to see if heroku manages to create a review app

**Comment by gvn** [comment]
This went stale...had to update the lockfile with the consolidation of deps and dev deps.

**Comment by alanmoo** [comment]
Got some conflicts...

**Pull request merged**
