### PR TITLE
Lint all scss files

### PR DESCRIPTION
**Pull request by arush0311**
Fixes https://github.com/mozilla/network/issues/543

### CODE REVIEW

**Comment by gvn** [comment]
@Pomax can you confirm this works on Windows?

**Comment by Pomax** [comment]
@gvn I don't get any errors on Windows during the test:scss task

**Comment by arush0311** [comment]
Hey! Since we have installed shx why dont we use that to standardize every script for windows too?

**Comment by gvn** [comment]
`shx` is being used to shim standard UNIX commands (like `rm`, `mkdir`, etc) for better portability, but it doesn't cover custom tools like `stylelint`.

**Pull request merged**
