### PR TITLE
Add a CODEOWNERS file

### LINKED ISSUE #726: Add CODEOWNERS file
docs: https://help.github.com/articles/about-codeowners/

Lets use a CODEOWNERS file to take advantage of required reviews for the `production` branch, as well as the awesome feature of automatically assigned reviews on pull requests.

### PR DESCRIPTION
**Pull request by cadecairos**
Added myself, @alanmoo, @Pomax, @gvn, and @gideonthomas as code owners, based on commit activity graphs for this repo. 

I think a global owner declaration might be redundant, now that I stop to look at it. I will remove it (or we can just manage code ownership and reviews using a team...?)

fixes #726

### CODE REVIEW

**Comment by gvn** [comment]
So what should I see with this? I did a test PR to the `CODEOWNERS` branch and didn't see any differences...

https://github.com/mozilla/network/pull/730

**Comment by alanmoo** [comment]
Hmmm, I turned on review requests on the CODEOWNERS branch and still can't seem to get it to work after 2 more test PRs

**Comment by cadecairos** [comment]
This might only affect protected branches. let me protect this branch and try opening a PR

**Comment by cadecairos** [comment]
maybe it doesn't work if the PR submitter is in the Code Owner list?

**Comment by cadecairos** [comment]
It could be that the CODEOWNERS file needs to be in the base branch of the repo for this feature to work.

**Pull request merged**
