### PR TITLE
Replace Arvo with Zilla Slab

### PR DESCRIPTION
**Pull request by fitojb**
Now that Zilla is in Google Fonts, let’s use that instead of Arvo.

### CODE REVIEW

**Comment by fitojb** [comment]
Zilla’s x-height is smaller, so I’ll be glad to tweak the font sizes as you wish.

**Comment by xmatthewx** [comment]
Thanks @fitojb!! We'll need a designer to review the site for font-size adjustments and any big quirks. It might take a few days given some vacation time right now. 

@flukeout - can you help @sabrinang or @taisdesouzalessa view this PR locally? Or just override the font in browser?

**Comment by flukeout** [comment]
Yes, definitely - ping me when ready to test @sabrinang / @taisdesouzalessa

**Comment by taisdesouzalessa** [comment]
@flukeout I'll be in the office tomorrow so we can take a look at this together? I'll have @sabrinang's eyes on that as well.

**Comment by flukeout** [comment]
For sure @taisdesouzalessa - just let me know.

**Comment by xmatthewx** [comment]
Note: you can see how this plays out in https://network.mozilla.org/style-guide/

**Pull request closed without merging**
